/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.TextField;
import java.util.*;
/**
 *
 * @author monster
 */
public class NewJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1() {
        initComponents();
    }
    /*public NewJFrame1(String ad){
            initComponents();
            HastaTC.setText(ad);
    }
    */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ad = new javax.swing.JLabel();
        Soyad = new javax.swing.JLabel();
        Eposta = new javax.swing.JLabel();
        Şifre = new javax.swing.JLabel();
        Adres = new javax.swing.JLabel();
        HastaAd = new javax.swing.JTextField();
        HastaSoyad = new javax.swing.JTextField();
        HastaEposta = new javax.swing.JTextField();
        HastaAdres = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        HastaKayıtOl = new javax.swing.JButton();
        HastaKayıtİptal = new javax.swing.JButton();
        HastaŞifre = new javax.swing.JPasswordField();
        TC = new javax.swing.JLabel();
        HastaTC = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kullanıcı Kayıt Ekranı");
        setLocation(new java.awt.Point(450, 150));

        Ad.setText("Ad:");

        Soyad.setText("Soyad:");

        Eposta.setText("E-Posta:");

        Şifre.setText("Şifre:");

        Adres.setText("Adres:");

        HastaAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HastaAdActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel8.setText("Hasta Kayıt Ekranı");

        HastaKayıtOl.setText("Kayıt Ol");
        HastaKayıtOl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HastaKayıtOl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HastaKayıtOlActionPerformed(evt);
            }
        });

        HastaKayıtİptal.setText("İptal");
        HastaKayıtİptal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HastaKayıtİptal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HastaKayıtİptalActionPerformed(evt);
            }
        });

        TC.setText("TC. Kimlik No:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(333, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(312, 312, 312))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(HastaKayıtOl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(HastaKayıtİptal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Adres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Şifre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Eposta, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addComponent(Soyad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Ad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(TC))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(HastaAd, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                            .addComponent(HastaSoyad)
                            .addComponent(HastaEposta, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                            .addComponent(HastaAdres)
                            .addComponent(HastaTC)
                            .addComponent(HastaŞifre))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel8)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(Eposta, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ad, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HastaAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Soyad, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HastaSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(HastaEposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Adres, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HastaAdres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Şifre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HastaŞifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TC)
                    .addComponent(HastaTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HastaKayıtOl)
                    .addComponent(HastaKayıtİptal))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HastaKayıtİptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HastaKayıtİptalActionPerformed
        // TODO add your handling code here:
        NewJFrame girişEkranıİptal = new NewJFrame();
        girişEkranıİptal.setVisible(true);
        dispose();
    }//GEN-LAST:event_HastaKayıtİptalActionPerformed

    private void HastaKayıtOlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HastaKayıtOlActionPerformed
        // TODO add your handling code here:
        NewJFrame girişEkranıKayıt = new NewJFrame();
        girişEkranıKayıt.setVisible(true);
        
        HashMap kayıt = new HashMap();
        
        
        
        /*
        int e = Integer.parseInt(HastaŞifre.getText());
        int f = Integer.parseInt(HastaTC.getText());
                
        kayıt.put("Ad", HastaAd);
        kayıt.put("Soyad", HastaSoyad);
        kayıt.put("Eposta", HastaEposta);
        kayıt.put("Adres", HastaAdres);
        kayıt.put("Şifre", e);
        kayıt.put("TC", f);
        
        //System.out.print(kayıt.containsValue(HastaAd));
        */
        
        dispose();
        
    }//GEN-LAST:event_HastaKayıtOlActionPerformed

    private void HastaAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HastaAdActionPerformed
       
    }//GEN-LAST:event_HastaAdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ad;
    private javax.swing.JLabel Adres;
    private javax.swing.JLabel Eposta;
    private javax.swing.JTextField HastaAd;
    private javax.swing.JTextField HastaAdres;
    private javax.swing.JTextField HastaEposta;
    private javax.swing.JButton HastaKayıtOl;
    private javax.swing.JButton HastaKayıtİptal;
    private javax.swing.JTextField HastaSoyad;
    private javax.swing.JTextField HastaTC;
    private javax.swing.JPasswordField HastaŞifre;
    private javax.swing.JLabel Soyad;
    private javax.swing.JLabel TC;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel Şifre;
    // End of variables declaration//GEN-END:variables
}
