/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.HashMap;
import javax.swing.JOptionPane;
import java.util.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
/**
 *
 * @author monster
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        PersonelNO = new javax.swing.JLabel();
        PersonelŞifre = new javax.swing.JLabel();
        PersonelGrirş = new javax.swing.JButton();
        PersonelŞifreGiriş = new javax.swing.JPasswordField();
        PersonelNOGiriş = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        HTCGiriş = new javax.swing.JLabel();
        HŞifreGiriş = new javax.swing.JLabel();
        HastaŞifreGiriş = new javax.swing.JPasswordField();
        HastaTCGiriş = new javax.swing.JTextField();
        HastaGiriş = new javax.swing.JButton();
        HastaKayıtOl = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        DoktorID = new javax.swing.JLabel();
        DoktorŞifre = new javax.swing.JLabel();
        DoktorIDGiriş = new javax.swing.JTextField();
        DoktorŞifreGiriş = new javax.swing.JPasswordField();
        DoktorGiriş = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hastane Otomasyonu");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(450, 150));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel1.setText("Hastane Otomasyon Sistemine Hoşgeldiniz");

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        PersonelNO.setText("Personel NO");

        PersonelŞifre.setText("Şifre ");

        PersonelGrirş.setText("Giriş");
        PersonelGrirş.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PersonelGrirş.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonelGrirşActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PersonelŞifre)
                    .addComponent(PersonelNO))
                .addGap(105, 105, 105)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PersonelNOGiriş, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PersonelŞifreGiriş, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(493, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PersonelGrirş)
                .addGap(109, 109, 109))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PersonelNO)
                    .addComponent(PersonelNOGiriş, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PersonelŞifre)
                    .addComponent(PersonelŞifreGiriş, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(PersonelGrirş)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Personel Girişi", jPanel2);

        HTCGiriş.setText("TC. Kimlik No ");

        HŞifreGiriş.setText("Şifre ");

        HastaŞifreGiriş.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HastaŞifreGirişActionPerformed(evt);
            }
        });

        HastaTCGiriş.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HastaTCGirişActionPerformed(evt);
            }
        });

        HastaGiriş.setText("Giriş");
        HastaGiriş.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HastaGiriş.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HastaGirişActionPerformed(evt);
            }
        });

        HastaKayıtOl.setText("Kayıt Ol");
        HastaKayıtOl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HastaKayıtOl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HastaKayıtOlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HTCGiriş)
                    .addComponent(HŞifreGiriş))
                .addGap(112, 112, 112)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(HastaTCGiriş, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HastaŞifreGiriş, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(470, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HastaGiriş)
                .addGap(40, 40, 40)
                .addComponent(HastaKayıtOl)
                .addGap(118, 118, 118))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HTCGiriş)
                    .addComponent(HastaTCGiriş, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HŞifreGiriş)
                    .addComponent(HastaŞifreGiriş, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HastaGiriş)
                    .addComponent(HastaKayıtOl))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Hasta Girişi", jPanel1);

        DoktorID.setText("Doktor ID");

        DoktorŞifre.setText("Şifre");

        DoktorGiriş.setText("Giriş");
        DoktorGiriş.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DoktorGiriş.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoktorGirişActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DoktorID)
                    .addComponent(DoktorŞifre))
                .addGap(120, 120, 120)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DoktorIDGiriş, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(DoktorŞifreGiriş))
                .addContainerGap(486, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DoktorGiriş)
                .addGap(161, 161, 161))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DoktorID)
                    .addComponent(DoktorIDGiriş, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoktorŞifre)
                    .addComponent(DoktorŞifreGiriş, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(DoktorGiriş)
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Doktor Girişi", jPanel3);

        jLabel2.setText("Şifre : 123       TC : 123");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(234, 234, 234))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(58, 58, 58)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HastaTCGirişActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HastaTCGirişActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HastaTCGirişActionPerformed

    private void HastaŞifreGirişActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HastaŞifreGirişActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HastaŞifreGirişActionPerformed
    
    private void HastaKayıtOlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HastaKayıtOlActionPerformed
        // TODO add your handling code here:
        NewJFrame1 hastakayıtEkranı = new NewJFrame1();
        hastakayıtEkranı.setVisible(true);
        dispose();
    }//GEN-LAST:event_HastaKayıtOlActionPerformed
        
    private void HastaGirişActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HastaGirişActionPerformed
        // TODO add your handling code here:
        /*
        String parola = "123";
        char[] parola_al = HastaŞifreGiriş.getPassword();
        String parolacalistir = String.valueOf(parola_al);
        
        String tc = "123";
        String tc_al = HastaTCGiriş.getText ();
        String tccalistir = String.valueOf(tc_al);
        */
        int hasta_TC = Integer.parseInt(HastaTCGiriş.getText());
        int hasta_şifre = Integer.parseInt(new String(HastaŞifreGiriş.getPassword()));
       /*parolacalistir.equals(parola) && tccalistir.equals(tc)*/
        if (authenticate(hasta_TC, hasta_şifre)) {
            
            Hastaİşlemleri hastagirişEkranı = new Hastaİşlemleri();
            hastagirişEkranı.setVisible(true);
            dispose();
            
        }
        else{
            String errorMessage = "TC. Kimlik No veya Şifre Hatalı";
            JOptionPane.showMessageDialog(rootPane, errorMessage);
            //dispose();
        }
        
    }//GEN-LAST:event_HastaGirişActionPerformed

    private boolean authenticate(int hasta_TC, int hasta_şifre) {
        String url = "jdbc:mysql://localhost:3306/hastane_otomasyon";
        String dbUser = "root";
        String dbPassword = "123456789";

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection = DriverManager.getConnection(url, dbUser, dbPassword);

            String query = "SELECT * FROM hasta_giriş WHERE hasta_TC=? AND hasta_şifre=? ";
            PreparedStatement preparedStatement = connection.prepareStatement(query);
            preparedStatement.setInt(1, hasta_TC);
            preparedStatement.setInt(2, hasta_şifre);

            ResultSet resultSet = preparedStatement.executeQuery();
            boolean loginSuccess = resultSet.next();

            resultSet.close();
            preparedStatement.close();
            connection.close();

            return loginSuccess;
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
            return false;
        }
    }
    private void PersonelGrirşActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonelGrirşActionPerformed
        // TODO add your handling code here:
        String parola = "123";
        char[] parola_al = PersonelŞifreGiriş.getPassword();
        String parolacalistir = String.valueOf(parola_al);
        
        String tc = "123";
        String tc_al = PersonelNOGiriş.getText ();
        String tccalistir = String.valueOf(tc_al);
       
        if (parolacalistir.equals(parola) && tccalistir.equals(tc)) {
            
            Personelİşlemleri personelgirişEkranı = new Personelİşlemleri();
            personelgirişEkranı.setVisible(true);
            dispose();
        }
        else{
            String errorMessage = "TC. Kimlik No veya Şifre Hatalı";
            JOptionPane.showMessageDialog(rootPane, errorMessage);
            //dispose();
        }
        
        
    }//GEN-LAST:event_PersonelGrirşActionPerformed

    private void DoktorGirişActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoktorGirişActionPerformed
        // TODO add your handling code here:

        String parola = "123";
        char[] parola_al = DoktorŞifreGiriş.getPassword();
        String parolacalistir = String.valueOf(parola_al);
        
        String tc = "123";
        String tc_al = DoktorIDGiriş.getText ();
        String tccalistir = String.valueOf(tc_al);
       
        if (parolacalistir.equals(parola) && tccalistir.equals(tc)) {
       
            Doktorİşlemleri doktorgirişEkranı = new Doktorİşlemleri();
            doktorgirişEkranı.setVisible(true);
            dispose();
        }
        else{
            String errorMessage = "TC. Kimlik No veya Şifre Hatalı";
            JOptionPane.showMessageDialog(rootPane, errorMessage);
            //dispose();
        }
    }//GEN-LAST:event_DoktorGirişActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DoktorGiriş;
    private javax.swing.JLabel DoktorID;
    private javax.swing.JTextField DoktorIDGiriş;
    private javax.swing.JLabel DoktorŞifre;
    private javax.swing.JPasswordField DoktorŞifreGiriş;
    private javax.swing.JLabel HTCGiriş;
    private javax.swing.JButton HastaGiriş;
    private javax.swing.JButton HastaKayıtOl;
    private javax.swing.JTextField HastaTCGiriş;
    private javax.swing.JPasswordField HastaŞifreGiriş;
    private javax.swing.JLabel HŞifreGiriş;
    private javax.swing.JButton PersonelGrirş;
    private javax.swing.JLabel PersonelNO;
    private javax.swing.JTextField PersonelNOGiriş;
    private javax.swing.JLabel PersonelŞifre;
    private javax.swing.JPasswordField PersonelŞifreGiriş;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
