
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author monster
 */
public class RandevuAlma extends javax.swing.JFrame {

    /**
     * Creates new form RandevuAlma
     */
    DefaultTableModel RandevuAlma = new DefaultTableModel();
    public RandevuAlma() {
        initComponents();
        RandevuTablosu.setModel(RandevuAlma);
        RandevuAlma.setColumnIdentifiers(new String [] {" Ad "," Soyad "," Saat "," Polikinlik "," Doktor "} );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        RandevuAd = new javax.swing.JTextField();
        RandevuSoyad = new javax.swing.JTextField();
        RandevuSaat = new javax.swing.JTextField();
        RandevuAl = new javax.swing.JButton();
        RandevuÇıkış = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        RandevuTablosu = new javax.swing.JTable();
        RandevuPolikinlik = new javax.swing.JComboBox<>();
        RandevuDoktor = new javax.swing.JComboBox<>();
        RandevuİptalEt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Adınız:");

        jLabel2.setText("Soyadınız:");

        jLabel3.setText("Randevu Saatinizi Yazınız:");

        jLabel4.setText("Gitmek İstediğiniz Polikinliği Seçiniz:");

        jLabel5.setText("Doktorunuzu Seçiniz:");

        RandevuAl.setText("Randevu Al");
        RandevuAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RandevuAlActionPerformed(evt);
            }
        });

        RandevuÇıkış.setText("Çıkış");
        RandevuÇıkış.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RandevuÇıkışActionPerformed(evt);
            }
        });

        RandevuTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(RandevuTablosu);

        RandevuPolikinlik.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dahilye", "Ortopedi", "Çocuk Hastalıkları", "KBB", "" }));
        RandevuPolikinlik.setToolTipText("");
        RandevuPolikinlik.setName(""); // NOI18N
        RandevuPolikinlik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RandevuPolikinlikActionPerformed(evt);
            }
        });

        RandevuDoktor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Samet Şahin", "Özgür Ateş", "Barış Aydin", "Yahya Kaymak", " " }));

        RandevuİptalEt.setText("Temizle");
        RandevuİptalEt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RandevuİptalEtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RandevuAl)
                            .addComponent(jLabel5))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(RandevuPolikinlik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(RandevuDoktor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RandevuÇıkış)
                                .addGap(51, 51, 51)
                                .addComponent(RandevuİptalEt, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RandevuAd)
                            .addComponent(RandevuSoyad)
                            .addComponent(RandevuSaat))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(RandevuAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(RandevuSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(RandevuSaat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(RandevuPolikinlik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(RandevuDoktor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RandevuAl)
                    .addComponent(RandevuÇıkış)
                    .addComponent(RandevuİptalEt))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RandevuPolikinlikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RandevuPolikinlikActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_RandevuPolikinlikActionPerformed

    private void RandevuÇıkışActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RandevuÇıkışActionPerformed
        // TODO add your handling code here:
        Hastaİşlemleri randevuEkranıİptal = new Hastaİşlemleri();
        randevuEkranıİptal.setVisible(true);
        dispose();
    }//GEN-LAST:event_RandevuÇıkışActionPerformed

    private void RandevuAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RandevuAlActionPerformed
        // TODO add your handling code here:
        String ad = RandevuAd.getText();
        String soyad = RandevuSoyad.getText();
        String saat = RandevuSaat.getText();
        Object polikinlik = RandevuPolikinlik.getSelectedItem();
        Object doktor = RandevuDoktor.getSelectedItem();

        RandevuAlma.addRow(new Object [] {ad , soyad , saat , polikinlik , doktor } );
       
    }//GEN-LAST:event_RandevuAlActionPerformed

    private void RandevuİptalEtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RandevuİptalEtActionPerformed
        // TODO add your handling code here:
        RandevuAd.setText(" ");
        RandevuSoyad.setText(" ");
        RandevuSaat.setText(" ");
        RandevuPolikinlik.setSelectedItem(" ");
        RandevuDoktor.setSelectedItem(" ");
        RandevuTablosu.setToolTipText(" ");
        
        
        
    }//GEN-LAST:event_RandevuİptalEtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RandevuAlma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RandevuAlma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RandevuAlma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RandevuAlma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RandevuAlma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RandevuAd;
    private javax.swing.JButton RandevuAl;
    private javax.swing.JComboBox<String> RandevuDoktor;
    private javax.swing.JComboBox<String> RandevuPolikinlik;
    private javax.swing.JTextField RandevuSaat;
    private javax.swing.JTextField RandevuSoyad;
    private javax.swing.JTable RandevuTablosu;
    private javax.swing.JButton RandevuÇıkış;
    private javax.swing.JButton RandevuİptalEt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
